user_api:
    resource: ../src/User/Api/Action/
    type: attribute
    prefix: /api/users
    name_prefix: 'users_'

resume_api:
    resource: ../src/Resume/Api/Action/
    type: attribute
    prefix: /api/resumes
    name_prefix: 'resumes_'

resume_public_api:
    resource: ../src/Resume/PublicApi/Action/
    type: attribute
    prefix: /public_api/resumes
    name_prefix: 'p_resumes_'

api_login_check:
    path: /api/login/
    methods: ['post']

api_refresh_token:
    path: /api/token/refresh/
    methods: ['post']

api_logout:
    path: /api/logout/